### PR TITLE
For concept review only: Failover from SeqSink to DurableSeqSink when exception thrown

### PR DESCRIPTION
**Pull request by bbrandt**
@nblumhardt,
This is super early stages, AKA not tested at all, but what do you think about having a failover sink in serilog/serilog-sinks-seq or is this more of something I would keep off to the side and maintain myself?  Is this conceptually sound, or can you see places I am going to get into trouble?

References:
http://stackoverflow.com/a/33539002
#10

### CODE REVIEW

**Comment by nblumhardt** [comment]
Interesting concept! Thanks for posting the example.

I can't see any issue with it - it really does (at first look) appear to present the best of both worlds... I may need to give it a bit more thought though.

The only implementation gotcha I see is that because the durable sink isn't instantiated unless there's been a problem, events written to the buffer file won't automatically be shipped on restart. Some kind of sniffing might be needed here, or perhaps the durable sink may need to be instantiated non-lazily.

Including something like this in the mainline version is definitely worth considering. Have you had a chance to try it out in practice yet?

Best regards,
Nick

**Comment by bbrandt** [comment]
Hi @nblumhardt , 
Sorry for the slow reply.  Had an all day sprint planning meeting yesterday.  Brutal.
We've had the opportunity to do a bit of testing on this now with a tester app that logs every few seconds.  Initially no file is created in the buffer location and we see the logs in Seq.  When I pull the network cable from the machine, the file is created and starts buffering up.  When I plug the cable back in, the logs are transmitted.  I'm fairly certain that in my haste I've left a few things out to make this a full implementation (like the tests), so I'll need to go over it again before making an official pull request.

Most of the apps apps my company supports need to allow the running of multiple instances, so we have to make the buffer file names unique per running instance.  So far ideas have been a GUID or the process ID appended to the buffer file name.  So, for us, event shipping on restart is already broken.  That is primarily why I was not concerned about the shipping on restart case.

Our other issue we will be running into is that buffer files are not cleaned up until the same process has been running for 3 days.  For us this means that most buffer files will never be cleaned up.  But we could be a unique case as we have to allow multiple running instances of the same app.  Likely, we'll end up with some service to clean out all old buffer files.

**Comment by bbrandt** [comment]
Here's the app.config being used during testing:

```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.2" />
    </startup>
  <appSettings>
    <add key="serilog:minimum-level" value="Verbose" />
    <add key="serilog:using:Seq" value="Serilog.Sinks.Seq" />
    <add key="serilog:write-to:Seq.serverUrl" value="http://server-name:5341" />
    <add key="serilog:write-to:Seq.bufferBaseFilename" value="%LOCALAPPDATA%\CompanyName\LogEntryGenerator" />
    <add key="serilog:write-to:Seq.failOverToDurable" value="True" />
    <add key="serilog:write-to:Seq.failoverRestrictedToMinimumLevel" value="Warning" />
  </appSettings>
</configuration>
```

**Comment by bbrandt** [comment]
Hi @nblumhardt,  
Do you know if we are unique in our `DurableSeqSink` usage in that we must run multiple application instances with unique buffer filenames and cannot ship on restart or is this in any way common?

**Comment by nblumhardt** [comment]
Hi Ben; I generally have encouraged people with desktop-type apps to use non-durable mode, but it would indeed be awesome to support this scenario better.

The coordination issue is the annoying one: if the storage is shared (say we switched even to persisting via some kind of limited database) the apps instances still need to elect which will send the batches to the server. Not impossible, but does complicate things a bit.

When I read your last email I started working through what it would take to create a separate "Seq Forwarder" Windows Service that could accept the logs via local HTTP and then durably ship them to  a remote Seq instance. Long-term it seems like a more robust and manageable option - what do you think?

I'm deep in working on another feature right now (that I think you'll also love :-)) so I can't pick up the forwarding service right now, but it's conceivable we could get a basic (non-MSI-deployed) version up on GitHub in the next month or so and start working at it that way...?

**Comment by bbrandt** [comment]
@nblumhardt, 
The "Seq Forwarder" service seems like it would really be the way to go.  I just ran into a similar architecture when experimenting with Consul and a few other solutions I've seen.  Clients communicate with a local service, then the service is responsible for syncing it up.  

Thanks for looking at this!  I look forward to hearing more about your new feature.

**Comment by nblumhardt** [comment]
Hi Ben,

A very early build and some details are now on our blog here: http://blog.getseq.net/help-us-test-seq-forwarder/

We'd love your feedback and input on this one, hope you're able to check it out.

Best regards,
Nick

**Comment by bbrandt** [comment]
Thanks Nick!  I'll check it out.

**Comment by ryanulit** [comment]
@nblumhardt, would using octopus deploy be another scenario that would cause issues with the buffer files?  Since it creates a new directory for each release (i.e. `C:\Octopus\Applications\dev\App.1.0.0`, `C:\Octopus\Applications\dev\App.1.0.1`, etc.) this would cause us to have a buffer file per release folder.  Would this be another situation where the Seq Forwarder would resolve these issues?

Thanks,
Ryan

**Comment by nblumhardt** [comment]
It's definitely problematic to log to a different buffer file with each deploy, @ryanulit 👍 

Using a path like `%APPDATA%\YourApp\Logs` for the buffer file is probably a less-intrusive way of solving this than deploying the forwarder, though.

**Pull request closed without merging**
